version: '3.6'
    
services:
    bigTable:
        command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
        image: google/cloud-sdk:latest
        volumes:
            - .:/opt/folder_name/my_application:delegated
        working_dir: /opt/folder_name/my_application
        environment:
            - BIGTABLE_EMULATOR_HOST=localhost:8086
        ports:
            - 8086:8086
